const userRepo = require("../repository/userRepo");
const db = require("../models/index");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const { sendWelcomeEmail, sendOtpEmail } = require("./emailService");
const saltRounds = 10;

exports.createUser = async (data) => {
  let plainPassword = data.password;
  let isAutoGenerated = false;

  // Auto-generate secure 8-character password using UUID only if no password provided
  if (!plainPassword || plainPassword.trim() === "") {
    const { v4: uuidv4 } = require("uuid");
    plainPassword = uuidv4().replace(/-/g, "").slice(0, 8);
    isAutoGenerated = true;
  }

  const salt = bcrypt.genSaltSync(saltRounds);
  const hash = bcrypt.hashSync(plainPassword, salt);

  const newData = {
    ...data,
    email: data.email ? data.email.toLowerCase() : data.email,
    password: hash,
  };

  const user = await userRepo.createUser(newData);
  const userId = user.userId;
  const role = user.role;

  try {
    if (role === "admin") {
      await db.companyModel.create({
        userId: userId,
        companyName: data.companyName || data.fullName || data.firstName || "My Company",
        contactEmail: user.email,
      });
    } else if (role === "interviewer") {
      const specializations = Array.isArray(data.specialization)
        ? data.specialization
        : (data.specialization ? [data.specialization] : ["System Design", "Algorithms & Data Structures", "Full Stack Architecture"]);
      const availabilitySlots = Array.isArray(data.availability) && data.availability.length > 0
        ? data.availability
        : ["Mon-Fri 06:00 PM - 07:00 PM", "Weekend 10:00 AM - 11:30 AM"];

      await db.interviewerModel.create({
        userId: userId,
        title: data.title || "Senior Software Engineer / Interviewer",
        department: data.department || data.domain || "Engineering",
        specialization: specializations,
        availability: availabilitySlots,
        isVerified: false, // Initially pending Super Admin approval
      });

      await db.profileModel.create({
        userId: userId,
        company: data.company || data.currentCompany || "Tech Industry Leader",
        headline: data.title ? `${data.title} at ${data.company || "Tech"}` : "Senior Technical Interviewer",
        experience: data.experience || data.yearsOfExperience || "5+ Years",
        phone: data.phone || null,
        skills: specializations,
        links: {
          linkedin: data.linkedinUrl || null,
          github: data.githubUrl || null,
        },
        bio: data.bio || `Specialized in evaluating ${specializations.slice(0, 3).join(", ")}. Passionate about mentoring and technical interviews.`,
      });
    } else if (role === "candidate") {
      await db.candidateModel.create({
        userId: userId,
        currentRole: data.currentRole || null,
        applicationStatus: "active",
      });
    }
  } catch (profileErr) {
    console.error("Warning: Could not create role profile row:", profileErr.message);
  }

  if (user && user.email) {
    sendWelcomeEmail(user, { plainPassword, isAutoGenerated }).catch((err) => {
      console.error("Failed to send welcome email:", err.message);
    });
  }

  const userObj = user.toJSON ? user.toJSON() : { ...user };
  userObj.plainPassword = plainPassword;
  userObj.isAutoGenerated = isAutoGenerated;

  return userObj;
};

exports.login = async (data) => {
  const { email, password } = data;

  const user = await userRepo.findUserByEmail(email);
  if (!user) {
    return {
      success: false,
      statusCode: 401,
      message: "Invalid email or password",
    };
  }

  if (!user.isActive) {
    return {
      success: false,
      statusCode: 403,
      message: "Account is inactive. Please contact support.",
    };
  }

  const isPasswordValid = await bcrypt.compare(password, user.password);
  if (!isPasswordValid) {
    return {
      success: false,
      statusCode: 401,
      message: "Invalid email or password",
    };
  }

  const userPayload = {
    userId: user.userId,
    username: user.username,
    email: user.email,
    firstName: user.firstName,
    lastName: user.lastName,
    role: user.role,
  };

  const token = jwt.sign(
    userPayload,
    process.env.JWT_SECRET,
    { expiresIn: process.env.JWT_EXPIRES_IN || "1d" }
  );

  return {
    success: true,
    statusCode: 200,
    message: "Login successful",
    token,
    user: userPayload,
  };
};

// Generate a secure 6-digit OTP
function generateOtp() {
  return Math.floor(100000 + Math.random() * 900000).toString();
}

exports.forgotPassword = async (email) => {
  if (!email) {
    return { success: false, statusCode: 400, message: "Email is required." };
  }

  const user = await userRepo.findUserByEmail(email);
  if (!user) {
    return {
      success: false,
      statusCode: 404,
      message: "No account found with this email address.",
    };
  }

  const otpCode = generateOtp();
  const otpExpires = new Date(Date.now() + 10 * 60 * 1000); // 10 minutes

  await userRepo.updateUser(user.userId, { otpCode, otpExpires });

  // Send OTP email (fire-and-forget — don't block response)
  sendOtpEmail({
    to: user.email,
    name: user.firstName || user.username || "User",
    otpCode,
  }).catch((err) => console.error("OTP email send error:", err.message));

  return {
    success: true,
    statusCode: 200,
    message: "A 6-digit OTP has been sent to your email address. It expires in 10 minutes.",
  };
};

exports.verifyOtp = async (email, otpCode) => {
  if (!email || !otpCode) {
    return { success: false, statusCode: 400, message: "Email and OTP code are required." };
  }

  const user = await userRepo.findUserByEmail(email);
  if (!user) {
    return { success: false, statusCode: 404, message: "No account found with this email." };
  }

  if (!user.otpCode || user.otpCode !== String(otpCode)) {
    return { success: false, statusCode: 400, message: "Invalid OTP code. Please try again." };
  }

  if (!user.otpExpires || new Date(user.otpExpires) < new Date()) {
    return { success: false, statusCode: 400, message: "OTP has expired. Please request a new one." };
  }

  return {
    success: true,
    statusCode: 200,
    message: "OTP verified successfully. You may now reset your password.",
  };
};

exports.resetPassword = async ({ email, resetToken, token, newPassword, password }) => {
  const targetPassword = newPassword || password;
  const targetToken = resetToken || token;

  if (!targetPassword) {
    return {
      success: false,
      statusCode: 400,
      message: "New password is required.",
    };
  }

  let user = null;
  if (targetToken) {
    user = await userRepo.findUserByResetToken(targetToken);
  }
  if (!user && email) {
    user = await userRepo.findUserByEmail(email);
  }

  if (!user) {
    return {
      success: false,
      statusCode: 400,
      message: "Invalid user or invalid password reset token.",
    };
  }

  if (user.resetTokenExpires && new Date(user.resetTokenExpires) < new Date()) {
    return {
      success: false,
      statusCode: 400,
      message: "Password reset token has expired. Please request a new link.",
    };
  }

  const salt = bcrypt.genSaltSync(saltRounds);
  const hash = bcrypt.hashSync(targetPassword, salt);

  await userRepo.updateUser(user.userId, {
    password: hash,
    resetToken: null,
    resetTokenExpires: null,
    otpCode: null,
    otpExpires: null,
  });

  return {
    success: true,
    statusCode: 200,
    message: "Password has been reset successfully. You can now log in with your new password.",
  };
};
